# This file contains non-secret configurations.

# API webserver configuration.
webserver:
  port: 8871
  endpoint: "/v1"
  subscriptions: "/ws"

# Prisma configuration.
prisma:
  endpoint: "http://localhost:4466/houston"
  secret: ~
  debug: false

# Logging configuration.
logging:
  level: "debug"

# Database connection.
# This is mostly for knexfile now.
# Also defined for Prisma service separately.
database:
  # Knex migrations
  migrations:
    # Table to store migrations
    tableName: migrations
    # Schema for migrations.
    # prisma deploy fails if this table exists in the same schema
    # as prisma tables.
    schemaName: public
    # Disable wrapping migrations with transaction
    # Currently disabling to allow better cooperation with prisma.
    disableTransactions: true

  # Knex connection
  connection:
    user: postgres
    password: postgres
    host: localhost
    port: 5432
    database: postgres

# Commander configuration.
commander:
  enabled: false
  host: localhost
  port: 50051

# Docker Registry configuration.
registry:
  port: 5000

# Email configuration.
email:
  # Enable sending emails.
  enabled: false

  # Open HTML emails in browser when sent.
  preview: false

  # The "from" address to use.
  reply: "noreply@astronomer.io"

  # The SMTP server URL.
  smtpUrl: ~

# Stripe configuration.
stripe:
  enabled: false
  secretKey: ~

# Set the length of a Cloud Trial
trial:
  # Cloud trial length in days
  length: 14

# Orbit configuration.
orbit:
  subdomain: app
  port: 5000

# Elasticsearch configuration for Houston to pull logs.
# This is passed striaght to the es client.
elasticsearch:
  # Enable or disable querying for logs in ES. This supersedes mock configuration below.
  enabled: false

  # Client configuration, passed directly to es-client constructor.
  client:
    host: ~
    log: error

  # If in NODE_ENV is development and this is enabled, generate sample log records.
  mockInDevelopment: true

  # Interval that data is grabbed and sent
  pollInterval: 1000

# Prometheus Metrics configuration
prometheus:
  # Sample data - false for no querying prometheus, true for querying prometheus.
  enabled: false
  host: localhost
  port: 9090
  pollInterval: 5000

# Charts live here.
# This is where the airflow chart is installed from.
repository: "https://helm.astronomer.io/"

# Helm configuration.
# These values are set at runtime and used for airflow deployments.
helm:
  baseDomain: ~
  registryAuthSecret: ~
  releaseName: ~
  releaseNamespace: ~
  releaseVersion: ~
  singleNamespace: false

# Auth configuration.
auth:
  # Local database (user/pass) configuration.
  local:
    enabled: true

  openidConnect:
    # Clock skew for slightly out-of-sync clocks
    clockTolerance: 0
    # Auth0 integration configuration.
    auth0:
      # This "enabled" flag is currently a little misleading.
      # The enabled flag refers only to showing the native
      # Auth0 button in the UI. The rest of the settings here
      # could potentially be used as to auth with Google/Github/etc
      # if those integrations are enabled, but do not have connection
      # information.
      enabled: false
      clientId: ~
      discoveryUrl: https://astronomerio.auth0.com
      authUrlParams:
        audience: "astronomer-ee"


    # Google oauth configuration.
    google:
      displayName: Google
      enabled: false
      # If blank we will go via Auth0
      clientId: ~
      discoveryUrl: https://accounts.google.com

    okta:
      enabled: false
      clientId: ~
      discoveryUrl: ~

  # Github via auth0
  github:
    enabled: false

# Houston JWT configuration.
jwt:
  # Development only: Passphrase to sign JWTs used to authenticate our GraphQL
  # API.
  #passphrase: ~

  # JWT / Cookie duration in milliseconds.
  authDuration: 86400000

  # Path to folder containing tls.crt and tls.key, used for signing JWT tokens
  # to authenticate against the Docker registry and Airflow FAB UI
  certPath: ~

  # Docker registry configuration.
  registry:
    certPath: ~
    issuer: ~
    service: ~

# Allow public signups.
publicSignups: false

# Require email confirmation.
emailConfirmation: true

# Subdomain under base domain.
subdomain: houston

# Format: ${SCOPE}.${RESOURCE}.${VERB}
roles:
  #
  # System
  #
  - id: SYSTEM_ADMIN
    name: System Admin
    permissions:
      - system.monitoring.view
      - system.iam.update
      - system.workspace.suspend
      - system.workspace.extendTrial
      - system.user.invite
      - system.user.delete
      - system.invite.get
      - system.deployment.delete
      - system.users.list

  - id: SYSTEM_EDITOR
    name: System Editor
    permissions:
      - system.monitoring.view
      - system.iam.update

  - id: SYSTEM_VIEWER
    name: System Viewer
    permissions:
      - system.monitoring.view

  #
  # Workspace
  #
  - id: WORKSPACE_ADMIN
    name: Workspace Admin
    permissions:
      - workspace.config.update
      - workspace.config.delete
      - workspace.invites.get
      - workspace.deployments.list
      - workspace.deployments.create
      - workspace.serviceAccounts.create
      - workspace.serviceAccounts.update
      - workspace.serviceAccounts.delete
      - workspace.iam.update
      - workspace.users.list
      - workspace.billing.update

  - id: WORKSPACE_EDITOR
    name: Workspace Editor
    permissions:
      - workspace.config.update
      - workspace.invites.get
      - workspace.users.list
      - workspace.deployments.list
      - workspace.deployments.create
      - workspace.serviceAccounts.create
      - workspace.serviceAccounts.update
      - workspace.serviceAccounts.delete

  - id: WORKSPACE_VIEWER
    name: Workspace Viewer
    permissions:
      - workspace.deployments.list
      - workspace.invites.get
      - workspace.users.list

  #
  # Deployment
  #
  - id: DEPLOYMENT_ADMIN
    name: Deployment Admin
    permissions:
      - deployment.config.get
      - deployment.config.update
      - deployment.config.delete
      - deployment.images.push
      - deployment.airflow.op
      - deployment.airflow.user
      - deployment.airflow.view
      - deployment.serviceAccounts.create
      - deployment.serviceAccounts.update
      - deployment.serviceAccounts.delete
      - deployment.logs.get
      - deployment.metrics.get

  - id: DEPLOYMENT_EDITOR
    name: Deployment Editor
    permissions:
      - deployment.config.get
      - deployment.config.update
      - deployment.images.push
      - deployment.airflow.user
      - deployment.airflow.view
      - deployment.serviceAccounts.create
      - deployment.serviceAccounts.update
      - deployment.serviceAccounts.delete
      - deployment.logs.get
      - deployment.metrics.get

  - id: DEPLOYMENT_VIEWER
    name: Deployment Viewer
    permissions:
      - deployment.config.get
      - deployment.airflow.view
      - deployment.logs.get
      - deployment.metrics.get

#
# Airflow Deployment Configurations
#
deployments:

  # Labels specifed here are applied to Airflow deployment namespaces.
  namespaceLabels: {}

  # Log out final helm values whenever they are generated, before deployment.
  logHelmValues: false

  # Default airflow version to deploy. This is used as the default image tag.
  defaultAirflowVersion: "1.10.4"

  # This is the database connection that we use to connect
  # and create other databases/schemas/users for each
  # individual airflow deployment.
  database:
    # If disabled, skip db creation.
    enabled: true

    # Keep the airflow databases around after a
    # deployment is deleted.
    retainOnDelete: false

    # If true, leave GRANTs in place for root user.
    # This lets users log in with the root creds and query
    # deployment databases.
    allowRootAccess: false

    # Connection details for root user.
    # This can also be overridden with a connection string.
    connection:
      user: postgres
      password: postgres
      host: localhost
      port: 5432
      database: postgres

  # Elasticsearch configuration for deployments.
  # Airflow clients access Elasticsearch differently.
  # Houston has full acces, while the deployments connect
  # via NGINX for auth.
  elasticsearch:
    enabled: false
    connection:
      host: localhost
      port: 9200

  # An astro unit defines the smallest billable unit
  # in the system. Default values are based on
  # the GCP n1-standard-1. CPU should always be expressed
  # in millicpu and memory should be expressed in Mibibytes.
  astroUnit:
    cpu: 100
    memory: 384
    pods: 1
    airflowConns: 5
    actualConns: 0.5
    price: 0

  # This defines how much extra capacity, in astro units,
  # that a user can expand a deployment to. This is currently
  # represented as a slider in the UI.
  maxExtraAu: 400

  # This defines the maximum size a pod can be in astro units.
  maxPodAu: 35

  # This defines all possible components for an airflow
  # deployment and the default AU to use for the kubernetes
  # resource requests, as well as its limits.
  components:
    - name: scheduler
      au:
        default: 5
        limit: 30
    - name: webserver
      au:
        default: 5
        limit: 30
    - name: statsd
      au:
        default: 2
        limit: 30
    - name: pgbouncer
      au:
        default: 2
        limit: 2
    - name: flower
      au:
        default: 2
        limit: 2
    - name: redis
      au:
        default: 2
        limit: 2
    - name: workers
      au:
        default: 10
        limit: 30
      extra:
        - name: terminationGracePeriodSeconds
          default: 600
          limit: 36000
        - name: replicas
          default: 1
          limit: 10

  # This defines which executors should be supported, as well
  # as the components required to run a particular
  # executor configuration.
  executors:
    - name: LocalExecutor
      enabled: true
      components:
        - scheduler
        - webserver
        - statsd
        - pgbouncer
    - name: CeleryExecutor
      enabled: true
      components:
        - scheduler
        - webserver
        - statsd
        - pgbouncer
        - workers
        - flower
        - redis
    - name: KubernetesExecutor
      enabled: true
      components:
        - scheduler
        - webserver
        - statsd
        - pgbouncer
      defaultExtraAu: 10

  # These are static configs that get merged directly into the values
  # passed to helm for each deployment.
  helm:
    # If enabled, deploy ServiceAccounts / Roles / RoleBindings
    # for components that require kubernetes apiserver access.
    rbacEnabled: true
    ingress:
      # Attach an airflow deployment to the system level ingress controller.
      enabled: true
    networkPolicies:
      # Enabled network polices to restrict the way pods can communicate.
      enabled: true
    pgbouncer:
      # Adds a pgbouncer service between the airflow pods (scheduler / webserver/ workers),
      # and the backend database.
      enabled: true
    # Allow scheduler/workers to launch pods by default. This is required for
    # the KubernetesPodOperator and KubernetesExecutor. This is what signals to apply the
    # required RoleBindings.
    allowPodLaunching: true
